/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_carlosdiaz;

import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Diaz
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_persona = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        rb_h = new javax.swing.JRadioButton();
        rb_m = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_vocacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rb_siT = new javax.swing.JRadioButton();
        rb_noT = new javax.swing.JRadioButton();
        rb_siC = new javax.swing.JRadioButton();
        rb_noC = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nacionalidad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        sp_edad = new javax.swing.JSpinner();
        genero = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        titulo = new javax.swing.ButtonGroup();
        jd_pais = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombrePais = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_himno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        b_color = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jcalendar = new com.toedter.calendar.JCalendar();
        covid = new javax.swing.ButtonGroup();
        popup_paises = new javax.swing.JPopupMenu();
        mi_agregar = new javax.swing.JMenuItem();
        mi_modificarP = new javax.swing.JMenuItem();
        mi_eliminarP = new javax.swing.JMenuItem();
        popup_personas = new javax.swing.JPopupMenu();
        mi_expulsar = new javax.swing.JMenuItem();
        mi_modificarPe = new javax.swing.JMenuItem();
        mi_eliminarPe = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_paises = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        l_hombres = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        l_mujeres = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        l_paises = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_infectados = new javax.swing.JTree();

        jLabel4.setText("Nombre");

        jLabel5.setText("Nacionalidad");

        jLabel6.setText("Apellido");

        genero.add(rb_h);
        rb_h.setText("Hombre");
        rb_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_hActionPerformed(evt);
            }
        });

        genero.add(rb_m);
        rb_m.setText("Mujer");

        jLabel7.setText("Edad");

        jLabel8.setText("Vocación");

        jLabel10.setText("Título");

        titulo.add(rb_siT);
        rb_siT.setText("Sí");

        titulo.add(rb_noT);
        rb_noT.setText("No");

        covid.add(rb_siC);
        rb_siC.setText("Positivo");

        covid.add(rb_noC);
        rb_noC.setText("Negativo");
        rb_noC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_noCActionPerformed(evt);
            }
        });

        jLabel11.setText("Covid");

        jLabel12.setText("AGREGAR PERSONA");

        jLabel13.setText("Sexo");

        jButton3.setText("Añadir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_personaLayout = new javax.swing.GroupLayout(jd_persona.getContentPane());
        jd_persona.getContentPane().setLayout(jd_personaLayout);
        jd_personaLayout.setHorizontalGroup(
            jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_personaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(307, 307, 307))
            .addGroup(jd_personaLayout.createSequentialGroup()
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jd_personaLayout.createSequentialGroup()
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel10)
                                .addGap(38, 38, 38)
                                .addComponent(rb_siT)
                                .addGap(18, 18, 18)
                                .addComponent(rb_noT))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_personaLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(38, 38, 38)
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_personaLayout.createSequentialGroup()
                                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(38, 38, 38)
                                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(64, 64, 64)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_personaLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(44, 44, 44)
                                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_personaLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(38, 38, 38)
                                    .addComponent(tf_vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(38, 38, 38)
                                .addComponent(rb_siC)
                                .addGap(18, 18, 18)
                                .addComponent(rb_noC))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(62, 62, 62)
                                .addComponent(rb_h)
                                .addGap(18, 18, 18)
                                .addComponent(rb_m)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jd_personaLayout.setVerticalGroup(
            jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_personaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_h)
                    .addComponent(rb_m)
                    .addComponent(jLabel13)
                    .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tf_vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rb_siC)
                    .addComponent(rb_noC)
                    .addComponent(jLabel10)
                    .addComponent(rb_siT)
                    .addComponent(rb_noT))
                .addGap(84, 84, 84)
                .addComponent(jButton3)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jLabel9.setText("jLabel9");

        jLabel16.setText("Nombre");

        jLabel18.setText("AGREGAR PAíS");

        jLabel19.setText("Fecha de Fundación");

        jLabel20.setText("Nombre del Himno");

        jLabel23.setText("Color de Bandera");

        b_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_colorMouseClicked(evt);
            }
        });

        jButton4.setText("Añadir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_paisLayout = new javax.swing.GroupLayout(jd_pais.getContentPane());
        jd_pais.getContentPane().setLayout(jd_paisLayout);
        jd_paisLayout.setHorizontalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_paisLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_paisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(103, 103, 103))
            .addGroup(jd_paisLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(38, 38, 38)
                                .addComponent(tf_nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_himno)
                                    .addComponent(b_color, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(27, 27, 27)
                        .addComponent(jcalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        jd_paisLayout.setVerticalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_paisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jcalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_himno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(b_color, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        mi_agregar.setText("Agregar persona");
        mi_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarActionPerformed(evt);
            }
        });
        popup_paises.add(mi_agregar);

        mi_modificarP.setText("Modificar");
        mi_modificarP.setActionCommand("mi_modificarP");
        mi_modificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarPActionPerformed(evt);
            }
        });
        popup_paises.add(mi_modificarP);

        mi_eliminarP.setText("Eliminar");
        mi_eliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarPActionPerformed(evt);
            }
        });
        popup_paises.add(mi_eliminarP);

        mi_expulsar.setText("Expulsarla del país");
        popup_personas.add(mi_expulsar);

        mi_modificarPe.setText("jMenuItem2");
        mi_modificarPe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarPeActionPerformed(evt);
            }
        });
        popup_personas.add(mi_modificarPe);

        mi_eliminarPe.setText("jMenuItem3");
        mi_eliminarPe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarPeActionPerformed(evt);
            }
        });
        popup_personas.add(mi_eliminarPe);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        t_paises.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        t_paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_paisesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_paises);

        l_hombres.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(l_hombres);

        jLabel1.setText("Hombres");

        l_mujeres.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(l_mujeres);

        jLabel2.setText("Mujeres");

        l_paises.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(l_paises);

        jLabel3.setText("Países");

        jButton1.setText("Crear persona");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear país");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton5.setText("--->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setText("Infectados");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Infectados");
        t_infectados.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        t_infectados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_infectadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_infectados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)))
                .addGap(138, 138, 138))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_hActionPerformed

    private void rb_noCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_noCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_noCActionPerformed

    private void b_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_colorMouseClicked

        b_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));

    }//GEN-LAST:event_b_colorMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        //AÑADIR PERSONA
        if(bloquearNacionalidad==true){
            tf_nacionalidad.setText(nombre_paisBloquear);       
        }
        String nacionalidad = tf_nacionalidad.getText();        //no importa pq se sobreescribiría
        String nombre = tf_nombre.getText();
        String apellido = tf_apellido.getText();
        String genero;
        if(rb_m.isSelected()){
            genero = "Mujer";
        } else{
            genero = "Hombre";
        }
        if(bloquearGenero==true){
            genero = genero_Bloquear;
        }
        int edad = (Integer) sp_edad.getValue();
        String vocacion = tf_vocacion.getText();
        boolean titulo;
        if(rb_siT.isSelected()){
            titulo = true;
        } else{
            titulo = false;
        }
        boolean covid;
        if(rb_siC.isSelected()){
            covid = true;
        } else{
            covid = false;
        }
        
        //AÑADO LA PERSONA A LA LISTA
        if(genero.equals("Hombre")){
            DefaultListModel modelo
                = (DefaultListModel) l_hombres.getModel();
            modelo.addElement(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid));
            l_hombres.setModel(modelo);
            
        } else if(genero.equals("Mujer")){
            DefaultListModel modelo
                = (DefaultListModel) l_mujeres.getModel();
            modelo.addElement(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid));
            l_mujeres.setModel(modelo);
            
        }
        tf_nacionalidad.setText(""); tf_nombre.setText(""); tf_apellido.setText(""); rb_h.setSelected(true); sp_edad.setValue(0);
        tf_vocacion.setText(""); rb_siT.setSelected(true); rb_siC.setSelected(true);
        
        //CREO O AÑADO A LA PERSONA AL PAíS
        
        
        DefaultTreeModel tModel = (DefaultTreeModel) t_paises.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) tModel.getRoot();
        
        int flag = 0;
        for (int i = 0; i < root.getChildCount(); i++) {
            DefaultMutableTreeNode k = (DefaultMutableTreeNode) root.getChildAt(i);
            Pais pSeleccionado = (Pais) k.getUserObject();
            //if (((Pais) root.getChildAt(i)).getNombre().equals(nacionalidad)) {       
                //Pais paisa = (DefaultMutableTreeNode) root.getChildAt(i);
            if (pSeleccionado.getNombre().equals(nacionalidad)) {                   //BUSCA SI YA EXISTE UNA NACIONALIDAD COMO LA DE ESTE WEY
                System.out.println(pSeleccionado);
                /*DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Persona(nombre,edad, nacionalidad));
                ((DefaultMutableTreeNode) root.getChildAt(i)).add(p);*/
                System.out.println("entraste donde ya habia");
                if(root.getChildAt(i).getChildAt(0).toString().equals("Hombres")){      //si ya están creadas estas carpetas, tons solo añadime al maje nuevo
                    if(genero.equals("Hombre")){
                        ((DefaultMutableTreeNode) root.getChildAt(i).getChildAt(0)).add     //hombres
                    (new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
                    } else if(genero.equals("Mujer")){
                        ((DefaultMutableTreeNode) root.getChildAt(i).getChildAt(1)).add     //mujeres
                    (new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
                    }
                    
                } else{
                    DefaultMutableTreeNode h = new DefaultMutableTreeNode("Hombres");
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mujeres");
                    //DefaultMutableTreeNode pais = new DefaultMutableTreeNode(nacionalidad);
                    ((DefaultMutableTreeNode) root.getChildAt(i)).add(h);
                    ((DefaultMutableTreeNode) root.getChildAt(i)).add(m);



                    if(genero.equals("Hombre")){
                        h.add(new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
                    } else if(genero.equals("Mujer")){
                        m.add(new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
                    }
                }
                
                flag = 1;
            } //fin if
        } //fin for  
        
        if(flag==0){
            DefaultMutableTreeNode pais = new DefaultMutableTreeNode(new Pais(nacionalidad, null, null, null));
            root.add(pais);
            
            DefaultListModel modelo = (DefaultListModel) l_paises.getModel();       //para añadirlo a la lista
            modelo.addElement(new Pais(nacionalidad, null, null, null));
            l_paises.setModel(modelo);

            DefaultMutableTreeNode h = new DefaultMutableTreeNode("Hombres");
            DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mujeres");
            pais.add(h);
            pais.add(m);

            if(genero.equals("Hombre")){
                h.add(new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
            } else if(genero.equals("Mujer")){
                m.add(new DefaultMutableTreeNode(new Persona(nacionalidad, nombre, apellido, genero, edad, vocacion, titulo, covid)));
            }
        }
        
        
        tModel.reload();
        jd_persona.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // AÑADIR PAíS
        if(bloquearNombrePais==true){
            tf_nombrePais.setText(nombre_paisBloquear);
        }
        String nombre = tf_nombrePais.getText();
        Date fFundacion = jcalendar.getDate();
        String nHimno = tf_himno.getText();
        Color color = b_color.getBackground();
            
        //AÑADO AL TREE DE PERSONAS
        DefaultTreeModel tModel = (DefaultTreeModel) t_paises.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) tModel.getRoot();
        int flag=0;                         //indica q pedos si ya existe el pais o sino para crearlo
        for (int i = 0; i < root.getChildCount(); i++) {
            DefaultMutableTreeNode k = (DefaultMutableTreeNode) root.getChildAt(i);
            Pais pSeleccionado = (Pais) k.getUserObject();
            if (pSeleccionado.getNombre().equals(nombre)) {                     //si ya existe esa nacionalidad
                if(bloquearNombrePais==false){//***
                    JOptionPane.showMessageDialog(this, "Error: ya existe ese país");   //tirarle advertencia
                    flag=1;
                }//***
                else{
                    pSeleccionado.setColor(color); pSeleccionado.setfFundacion(fFundacion); pSeleccionado.setnHimno(nHimno);
                }
            }
        }
        
        if(flag==0 && bloquearNombrePais==false){                                                                //sino, tons crearlo normal
            DefaultMutableTreeNode pais = new DefaultMutableTreeNode(new Pais(nombre, fFundacion, nHimno, color));
                root.add(pais);

                DefaultMutableTreeNode h = new DefaultMutableTreeNode("Hombres");
                DefaultMutableTreeNode m = new DefaultMutableTreeNode("Mujeres");
                pais.add(h);
                pais.add(m);
                tModel.reload();
                
        //AÑADO AL JLIST
        DefaultListModel modelo = (DefaultListModel) l_paises.getModel();
        modelo.addElement(new Pais(nombre, fFundacion, nHimno, color));
        l_paises.setModel(modelo);
        }
        tf_nombrePais.setText(""); jcalendar.setDate(new Date()); tf_himno.setText(""); b_color.setBackground(Color.red);
        jd_pais.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // DESPLEGAR MENU DE CREAR PERSONA 
        jd_persona.setModal(true);        
        jd_persona.pack();
        jd_persona.setLocationRelativeTo(this);        
        jd_persona.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // DESPLEGAR MENU DE CREAR PAIS
        jd_pais.setModal(true);        
        jd_pais.pack();
        jd_pais.setLocationRelativeTo(this);        
        jd_pais.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void t_paisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_paisesMouseClicked
        // CLICK DERECHO SOBRE EL TREE
        if (evt.isMetaDown()) {
            int row = t_paises.getClosestRowForLocation(evt.getX(), evt.getY());
            t_paises.setSelectionRow(row);

            Object node = t_paises.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) node;
            
            if (nodo_seleccionado.getUserObject() instanceof Pais) {
                System.out.println("es un pais");
                pais_seleccionado = (Pais) nodo_seleccionado.getUserObject();
                        nombre_paisBloquear = pais_seleccionado.getNombre();
                        System.out.println(nombre_paisBloquear);
                popup_paises.show(evt.getComponent(), evt.getX(), evt.getY());
                
            } else if(nodo_seleccionado.getUserObject() instanceof Persona){
                persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                    nombre_paisBloquear = persona_seleccionada.getNacionalidad();       //bloqueo esta
                    genero_Bloquear = persona_seleccionada.getGenero();                 //bloqueo esta otra
                popup_personas.show(evt.getComponent(), evt.getX(), evt.getY());
                
            }
        }
        
    }//GEN-LAST:event_t_paisesMouseClicked

    private void mi_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarActionPerformed
        // AÑADIR CON EL POPUP
        bloquearNacionalidad = true;
        
        jd_persona.setModal(true);        
        jd_persona.pack();
        jd_persona.setLocationRelativeTo(this);        
        jd_persona.setVisible(true);
    }//GEN-LAST:event_mi_agregarActionPerformed

    private void mi_modificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarPActionPerformed
        // MODIFICAR EL FOKING PAIS
        bloquearNombrePais = true;
        
        jd_pais.setModal(true);        
        jd_pais.pack();
        jd_pais.setLocationRelativeTo(this);        
        jd_pais.setVisible(true);
    }//GEN-LAST:event_mi_modificarPActionPerformed

    private void mi_eliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarPActionPerformed
        // ELIMINAR PAIS
        int r = JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar país?", "", JOptionPane.YES_NO_OPTION);

            if (r == 0) {
                DefaultTreeModel m = (DefaultTreeModel) t_paises.getModel();
                m.removeNodeFromParent(nodo_seleccionado);
            }
    }//GEN-LAST:event_mi_eliminarPActionPerformed

    private void mi_eliminarPeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarPeActionPerformed
        // ELIMINAR PERSONA
    }//GEN-LAST:event_mi_eliminarPeActionPerformed

    private void mi_modificarPeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarPeActionPerformed
        // MODIFICAR PERSONA
        bloquearNombrePais = true;
        bloquearGenero = true;
        
        jd_persona.setModal(true);        
        jd_persona.pack();
        jd_persona.setLocationRelativeTo(this);        
        jd_persona.setVisible(true);
    }//GEN-LAST:event_mi_modificarPeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // INFECTADOS PASAN A JTREE
        DefaultTreeModel tModel = (DefaultTreeModel) t_paises.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) tModel.getRoot();
        /*System.out.println(root.getChildCount());
        System.out.println(root.getChildAt(0).getChildAt(0).getChildCount());
        System.out.println(root.getChildAt(0).getChildAt(1).getChildCount());*/
        System.out.println("");
        System.out.println("INFECTADOS:");
        for (int i = 0; i < root.getChildCount(); i++) {
            if(root.getChildAt(i).getChildCount()!=0){        //si el pais si tiene hijos

                if(root.getChildAt(i).getChildAt(0).getChildCount()!=0){  //si hombres si tiene hijos
                    for (int j = 0; j < root.getChildAt(i).getChildAt(0).getChildCount(); j++) {
                        nodo_seleccionado = (DefaultMutableTreeNode) root.getChildAt(i).getChildAt(0).getChildAt(j);
                        persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                        if(persona_seleccionada.isCovid()==true){
                            System.out.println(persona_seleccionada);   //mirar consola para comprobar q estan buenos
                            //AÑADO LA PERSONA AL JTREE DE INFECTADOS 
                        }
                    }
                    
                }
                if(root.getChildAt(i).getChildAt(1).getChildCount()!=0){  //si mujeres si tiene hijos
                    for (int j = 0; j < root.getChildAt(i).getChildAt(1).getChildCount(); j++) {
                        nodo_seleccionado = (DefaultMutableTreeNode) root.getChildAt(i).getChildAt(1).getChildAt(j);
                        persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                        if(persona_seleccionada.isCovid()==true){
                            System.out.println(persona_seleccionada);   //mirar consola para comprobar q estan buenos
                            //AÑADO LA PERSONA AL JTREE DE INFECTADOS
                        }
                    }
                }
                
                
            }
            
            
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void t_infectadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_infectadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t_infectadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_color;
    private javax.swing.ButtonGroup covid;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JCalendar jcalendar;
    private javax.swing.JDialog jd_pais;
    private javax.swing.JDialog jd_persona;
    private javax.swing.JList<String> l_hombres;
    private javax.swing.JList<String> l_mujeres;
    private javax.swing.JList<String> l_paises;
    private javax.swing.JMenuItem mi_agregar;
    private javax.swing.JMenuItem mi_eliminarP;
    private javax.swing.JMenuItem mi_eliminarPe;
    private javax.swing.JMenuItem mi_expulsar;
    private javax.swing.JMenuItem mi_modificarP;
    private javax.swing.JMenuItem mi_modificarPe;
    private javax.swing.JPopupMenu popup_paises;
    private javax.swing.JPopupMenu popup_personas;
    private javax.swing.JRadioButton rb_h;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_noC;
    private javax.swing.JRadioButton rb_noT;
    private javax.swing.JRadioButton rb_siC;
    private javax.swing.JRadioButton rb_siT;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTree t_infectados;
    private javax.swing.JTree t_paises;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_himno;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrePais;
    private javax.swing.JTextField tf_vocacion;
    private javax.swing.ButtonGroup titulo;
    // End of variables declaration//GEN-END:variables

    DefaultMutableTreeNode nodo_seleccionado;
    Pais pais_seleccionado;
    Persona persona_seleccionada;
    String nombre_paisBloquear;
    String genero_Bloquear;
    boolean bloquearNacionalidad=false;     //para la hora de modificar
    
    boolean bloquearNombrePais = false;     //midiificar el nombre del pais en modificar pais
    boolean bloquearGenero = false;
}
